spring:
  profiles:
    active: local
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    topic: "library-events"
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      group-id: library-events-listener-group
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
